name: poc

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run vulnerable pattern
        uses: S3DFX-CYBER/poc-action@main
        with:
          github_auth_token: ${{ secrets.GITHUB_TOKEN }}
